name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: mkdir obj
      run: mkdir obj
    - name: ./configure dev
      run: ./configure dev
    - name: make check11
      run: make check11
    - name: make check14
      run: make check14
    - name: make check17
      run: make check17
